### ISSUE TITLE
Changes to make before transferring to Build-A-Cell

### ISSUE THREAD

**Issue by murrayrm** [BuildACell/BioCRNPyler#1]
This issue is intended to collect comments on things that we should change (if anything) before moving repository back over to the build-a-cell project.

Here are a couple of things to consider:

* We should put in a `README` file that contains at least some info on the package, since that will show up on the main repository page.

* We need to add the `LICENSE` file back in.  This reference in several of the files but is not currently in the repository.

* I suggest using a slightly more standard set of package conventions:
  * Add `__init__.py` file to allow import of the `txtl` package
  * Add `setup.py` file to install the package
  * Create `tests` subdirectory with unit tests that use `unittest` framework
  * Move current `Tests` to `examples` (or something) since they are not unit tests

* When all of this is working,, it should be possible to use the command
```
python setup.py test
```
to run unit tests.

* I suggest renaming `txtl.py` to something like `extract.py` since that is what it implements.  Combined with adding a package initialization file `__init__.py`, this will allow `txtl` to be used as a package name and eliminate the need to import each module individually (though that is still allowed if someone wants to do it that way).

* We should add back in the `.travis.yml` file to get continuous integration tests working again.

Most of the files required are in the old repository and just need to be copied over (with modifications as needed).

**Comment by WilliamIX** [comment]
Thanks Richard, I will start working in this direction. Can you send me some documentation / links about this unittest framework and the continuous integration tests? I Don't know really know what these things are.

**Comment by murrayrm** [comment]
Python unit test framework: https://docs.python.org/3/library/unittest.html

Travis CI (continuous integration): https://docs.travis-ci.com/user/for-beginners/

The combination of these two tools allows you to have all commits the the repository be tested against a set of (hopefully fairly complete) unit tests so that developers can flag when something breaks.

**Comment by zoltuz** [comment]
I've tried to address the issues listed above in #23, if @WilliamIX accepts the changes, then we could merge the current code base to the build-a-cell repository (along with the open issues).

**Comment by zoltuz** [comment]
@WilliamIX please have a look here about how to setup travis CI on your account:
https://github.com/mbonaci/mbo-storm/wiki/Integrate-Travis-CI-with-your-GitHub-repo#integrate-your-github-project-with-travis-ci
The correct config file is already the push request.
You might need to rename your repo to _biocrnpyler_ before you set this up.

**Comment by zoltuz** [comment]
Hi @murrayrm , I think we are ready to move the repo to build-a-cell, all above mentioned features are working. 
@WilliamIX probably the fastest way is to transfer ownership:
https://help.github.com/en/articles/transferring-a-repository

**Comment by murrayrm** [comment]
Looks good to me.  Thanks for all of the hard work!  

@WilliamIX You need to initiate this.  Transfer to `BuildACell` and then I should be able to pick it up, add everyone back as collaborators, and sort out what to do with the legacy `txtlsim-python` (probably remove it, unless there is something there that we want to keep).

**Comment by WilliamIX** [comment]
Did the transfer - please let me know if I should do anything else.

**Comment by murrayrm** [comment]
Transfer complete!
