### ISSUE TITLE
Automatic testing on dev branch

### ISSUE THREAD

**Issue by WilliamIX** [BuildACell/BioCRNPyler#104]
Right now, I don't think travis and coverage automatically test the dev branch on github - would it be possible to make them test that branch as well? @zoltuz 

My proposed development cycle is as follows:
1. Developers use their own branches to make new features to the software
2. These changes are eventually pushed to the "dev" branch where they can be integrated with other ongoing changes, tested, etc. Before merging with the dev branch, python setup.py test should work locally and either: A) a testing notebook is made and/or B) comprehensive test cases are made.
3. Periodically, we will merge the dev branch into master. This will in effect be a new release of the software.

**Comment by zoltuz** [comment]
Travis is triggered for each commit/PR regardless of the branch. There's an &#10060; or &#10004; next to each commit: 

[master](https://github.com/BuildACell/BioCRNPyler/commits/master) branch

[dev](https://github.com/BuildACell/BioCRNPyler/commits/dev) branch

I agree with the proposed cycle, I suggested something similar in #97

**Comment by ayush9pandey** [comment]
I guess this issue can be closed now
