### ISSUE TITLE
Need version requirement on Bokeh

### ISSUE THREAD

**Issue by sclamons** [BuildACell/BioCRNPyler#106]
Biocrnpyler throws import errors when using old versions of Bokeh. Bokeh-0.12.4 breaks; Bokeh-2.1.1 works. Fix: 

add version to bokeh in requirements.txt

**Comment by zoltuz** [comment]
For some reason, the bokeh version is pinned down to 1.4.0 in the [setup.py](https://github.com/BuildACell/BioCRNPyler/blob/master/setup.py). 
According to the file history, Andrey @dr3y  made this change in [706b9ecf](https://github.com/BuildACell/BioCRNPyler/commit/706b9ecf9f0269d7c539b554b5ec38e7742173f2#diff-2eeaed663bd0d25b7e608891384b7298)
Andrey is there a reason for fixing the version for bokeh? Can we use the latest version?

**Comment by dr3y** [comment]
i think it might be ok with a > there. I know they were changing how the graph plotting features get imported in newer versions of bokeh but i should just keep up to date with that

**Comment by dr3y** [comment]
wait but if the version is specified then it shouldnt have these import problems, right?

**Comment by sclamons** [comment]
I was able to install biocrnpyler using bokeh 0.12.4, which shouldn't happen if we have a higher Bokeh version pinned.

**Comment by zoltuz** [comment]
When you do 
```
python setup.py install
# or
pip install . 
```
Then the installer looks up the dependencies from the setup.py and installs them. After that you can install any version of Bokeh if you choose to do so. It won't be checked by any mechanism in pip or python. 

If you peek into the [Travis log](https://api.travis-ci.com/v3/job/352404583/log.txt) (a virtual machine that installs BioCRNPlyer after each commit to GitHub). This is what you see:
```
Searching for bokeh==1.4.0
Reading https://pypi.org/simple/bokeh/
Downloading https://files.pythonhosted.org/packages/de/70/fdd4b186d8570a737372487cc5547aac885a1270626e3ebf03db1808e4ed/bokeh-1.4.0.tar.gz#sha256=c60d38a41a777b8147ee4134e6142cea8026b5eebf48149e370c44689869dce7
Best match: bokeh 1.4.0
Processing bokeh-1.4.0.tar.gz
Writing /tmp/easy_install-cdmlj6vp/bokeh-1.4.0/setup.cfg
Running bokeh-1.4.0/setup.py -q bdist_egg --dist-dir /tmp/easy_install-cdmlj6vp/bokeh-1.4.0/egg-dist-tmp-i0d1dzdf
```

**Comment by ayush9pandey** [comment]
This has been fixed in the new setup.py : Try `pip install biocrnpyler[all]` : It will install bokeh>=1.4.0 along with other dependencies.
