### ISSUE TITLE
Installing version control and setup.py install

### ISSUE THREAD

**Issue by WilliamIX** [BuildACell/BioCRNPyler#111]
Issue: currently if we change the version of biocrnpyler, multiple eggs will get installed and jupyter/python don't necessarily use the newest egg. Currently we have stopped doing any kind of version control - but I think this is more of a hack than a solution. I know at some point, we want installation via pip to work. However, I also think that python setup.py install should work with versions.

Here is a thought on how to make this work:
in setup.py install, look for multiple biocrnpyler eggs. If multiple eggs are found, give the option (via the terminal) to delete the old eggs by typing Y or not delete them by typing N.

The hope here is to get back to using versions soon with or without pip.

 @zoltuz @murrayrm @ayush9pandey do you have any thoughts?

**Comment by murrayrm** [comment]
I'm not an expert on this, but here is what I would suggest:

* We should separate out "standard" usage from "beta" usage from "developer" usage.  

    * Standard usage is someone who is going to create a conda environment, install the latest version of bioCRNpyler (via pip).  This is the easy case and for this we should make sure that standard versioning is in place.

    * "Beta" usage is what we have been doing in classes and bootcamp: we are making active modifications to bioCRNpyler on GitHub and students are updating the package using git.  For this, I would suggest not setting the version (or setting it to "beta") so that there is only one version installed and it gets overwritten. 

    * "Developer" usage is similar, except that someone is actively develop and testing code => they may not want to install at all.  Many packages allow you to do `python setup.py develop` which sets things up so that Python picks up the code from the source directory => you don't need to reinstall at all (more information [here](https://stackoverflow.com/questions/19048732/python-setup-py-develop-vs-install)).

* I would try to get `setup.py` to be as generic as possible, using `setuptools` with minimal customization.  This will let us stay maximally compatible with conventions used by the broader Python community, including things like `python setup.py develop` functionality and proper versioning.  Details on `setuptools` is [here](https://setuptools.readthedocs.io/en/latest/index.html).

**Comment by zoltuz** [comment]
A similar issue was discussed in #97 and the conclusion was to use this workflow:

### first time
```
mkdir biocrnplyer
git clone https://github.com/BuildACell/BioCRNPyler.git biocrnplyer
cd biocrnplyer
pip install --user .
``` 
### getting an update
```
pip uninstall biocrnpyler
git pull 
pip install --user .
```

Given Richard's comments for the developers and 'beta' users:
```
pip install --user -e .
```

As a last resort one can delete the conda/virtual/pipenv environment folder and all the packages within. Not so elegant, but does the job.

**Comment by zoltuz** [comment]
I've created a mini installation guide here: https://github.com/BuildACell/BioCRNPyler/wiki/How-to-install-BioCRNPyler
Feel free to edit it. Once, everyone is happy with it, we can link this guide in the README.md.

**Comment by ayush9pandey** [comment]
This is fixed now : https://pypi.org/project/biocrnpyler/
