### ISSUE TITLE
True/False for leak isn't working

### ISSUE THREAD

**Issue by zjuradoq** [BuildACell/BioCRNPyler#115]
When working with example "4. Promoters, Transcriptional Regulation, and Gene Regulatory Networks.ipynb" I found that when I changed the leak to True or False the model was not effected. Image below shows result for two different values of leak when on or off.
![LeakCheck](https://user-images.githubusercontent.com/32440023/85962699-efd8ff80-b966-11ea-8c20-4b96cab344ac.JPG)

**Comment by WilliamIX** [comment]
Thanks Zoila - I see the issue and it will be fixed in the next release. If this is a major issue for your work, I suggest you use RegulatedPromoter instead of Activatable/Repressible Promoter.

**Comment by zoltuz** [comment]
Hi @zjuradoq, thanks for reporting this. This issue has been solved (thanks @WilliamIX! ) and the dev branch now contains the bugfix. 

If you want to give a try, you can install biocrnpyler using the code from the dev branch:
https://github.com/BuildACell/BioCRNPyler/wiki/How-to-install-BioCRNPyler#installing-the-dev-branch
