### ISSUE TITLE
CRN Species Overhaul

### ISSUE THREAD

**Issue by WilliamIX** [BuildACell/BioCRNPyler#120]
@zoltuz is currently working on a CRN Reaction overhaul. At some point, I think we will need to do something similar for Species. 

## Design Question 1: Should CRN Species should be "univerisal" pointers ie if two Species are equivalent, they point to the same object?

Recapping a discussion with @zoltuz : the issue is that multiple Species objects (different python pointers) can be the same in terms of their defined `==` functionality due to their string representation. For example:

`S1, S2 = Species("S"), Species("S")` are two distinct objects which will be viewed as equal `S1 == S2` ==> `True`

However, if I now change S1, like `S1.material_type = "m"`, `S1 == S2` ==> `False`. Importantly, S1 is a different pointer than S2 and thereby does not effect S2. 

_In other words, does it make sense for changing S1 to also change S2 if S1 is created so that it is equal to S2? The use case here is that I compile a CRN and then change some species in that CRN. This change can then propagate back through the entire compiled CRN. In the current implementation, this will definitely not occur consistently because many equivalent species are constructed as different python objects._

## Design Question 2: How can we represent species with multiple binding sites (eg a long piece of DNA) to easily create bound Complexes where a binding Species binds to a specific Site? Does this require new representations of species beyond the string representation we currently use?

In particular, I am referencing a discussion in https://github.com/BuildACell/BioCRNPyler/pull/102 where Andrey and I discuss how to use Species to represent binding positions on a greater piece of DNA. I will reiterate the example the discussed in the PR as well as a crucial issue Andrey brought up that seems to imply we need an overhaul.

**Basic Idea:**
Introduce a new Species class SubSpecies(Species). SubSpecies can ONLY exist inside a ScaffoldSpecies (there is probably a better name) which is effectively an OrderedComplexSpecies made up of SubSpecies. Importantly, SubSpecies know about their containing ScaffoldSpecies and use it's name. However, when a SubSpecies is passed into ComplexSpecies or OrderedComplexSpecies, the resulting Species object is automatically placed inside of the ScaffoldSpecies which contains the Subspecies.

I will illustrate this with an example of two binding sites B1 and B2 in a polymer P which can be bound to A1 and A2, respectively. Note that this is a combinatorial system with 4 possible states.

`A1, A2 = Species("A2"), Species("A1")`

`B1, B2 = SubSpecies("B1"), SubSpecies("B2")`

`P = ScaffoldSpecies ([B1, B2]) `==> B1 and B2 can now only be used in a reaction or ComplexSpecies after they are placed inside a Parent Species. If B1 or B2 were used before this line of code, an error would occur.

`C1 = ComplexSpecies([A1, B1])` ==> Returns `ScaffoldSpecies([ComplexSpecies([A1, B1]), B2])` Notice that A1 binds to B1 inside of the ScaffoldSpecies that contains B1 and B2.

`C2 = ComplexSpecies([A2, B2])` ==> Returns `ScaffoldSpecies ([B1, ComplexSpecies([A2, B2])])`

`C3 = ComplexSpecies([A1, C1.species[B1])` ==> Returns `ScaffoldSpecies([ComplexSpecies([A1, B1]), B2]), ComplexSpecies([A2, B2])])`. Notice that ScaffoldSpecies can access their SubSpecies easily. The proposed indexing probably needs to be smarter for cases where there are multiple copies of the same SubSpecies in a ScaffoldSpecies - but that is doable, maybe by integer indexing.

`C4 = ComplexSpecies([A2, C2.species[B2]) `==> Returns `ScaffoldSpecies([ComplexSpecies([A1, B1]), B2]), ComplexSpecies([A2, B2])])` which is equal to C3.

`D1 = ComplexSpecies([A1, P])` ==> returns `ComplexSpecies([A1, ScaffoldSpecies([B1, B2])])` which is distinct from C1...C4.

This Binding behavior can be programmed by adding a helper function to ComplexSpecies (and ordered ComplexSpecies) which can be used in the` __new__` class method. This method is called before init and would allow for ComplexSpecies and OrderedComplexSpecies to return ScaffoldSpecies instead of their respective class types.

Finally, if a subspecies is used in a reaction, it will be equivalent to using its containing ScaffoldSpecies. This can be accomplished by making sure the string representation of the SubSpecies is the same as it's ScaffoldSpecies.

**Point 1:** For this to work, every ScaffoldSpecies will need a unique copy of each SubSpecies. Notice that this could conflict with the idea of universal species in design question 1.

**Point 2:** How do two ScaffoldSpecies bind together? Below is an example:

`A1, A2, B1, B2= SubSpecies("A1"), SubSpecies("A2"), SubSpecies("B1"), SubSpecies("B2")`

`PA = ScaffoldSpecies ([A1, A2])`

`PB = ScaffoldSpecies ([B1, B2])`

To make PA bind to PB with site A1 attaching to B1 we should be able to say very simply:

`C = ChemicalComplex([A1, B1])`

However, I think @dr3y correctly pointed out that it isn't obvious what this will return. Additionally, I worry that `C2 = ChemicalComplex([B1, A1])` will not end up being the same as C, which isn't the behavior we want.

What this suggests to me is that we need a better internal Species representation than strings. I believe this problem has been dealt with by the DNA-strand-displacement community using [graph-isomorphisms](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4896506/). ScaffoldSpecies and SubSpecies might be a way to do this - although this example points out that a linear sequence representation is insufficient for two ScaffoldSpecies binding together. 

_In other words, we might want to ultimately think of ScaffoldSpecies and SubSpecies as a graph. SubSpecies (and regular Species) are nodes in the graph. ComplexSpecies would groups of Species/SubSpecies inside the graph. ScaffoldSpecies would be the entire graph. **This level of abstraction would require a completely new way to represent species (including new naming conventions) and new definitions of equality between graphs.** The question is, how important is this kind of functionality? My initial thought is that for systems like integrases, DNA-strand displacement systems, complex RNAzymes, Scaffold Proteins, etc we will need this level of generality. But maybe there is a simpler solution?_

**Comment by zoltuz** [comment]
Hi @WilliamIX 
I'll add a more detailed comment soon, but please have a look at #103. In the new propensity model, I've refactored most of the Reaction class, let's coordinate, most probably most of the features are there already!

**Comment by zoltuz** [comment]
Addressing design question 1:
As a user, if I want to replace a particular species in the CRN, which is present in multiple reactions, then I would expect that species gets changed everywhere. Having multiple 'copies' of the same species is fine, but we need to have a robust updating mechanism that keeps everything in sync.

Given the 'distributed' nature of the reactions, i.e. they only meet when the CRN object is initialized, I would do the Species consolidation there: 
```python
A= Species('A')
A_other =Species('A')
CRN = ChemicalReactionNetwork(species=[A,A_other], reactions=[])
CRN.species # this returns only on Species 
```
On a semi-related note, I'm confused by this `material_type` attribute for Species. What is the purpose of that? It seems to be a species is 'looking' back what higher-level object is created a given species. If it is important, what higher-level object (DNA, promoter, protein) has created a species, then it should be the other way around, for example, a protein is composed of two types a component and a species: 
```
class Protein(Component, Species):
     def get_species():
         return self
```
Am I missing something here?

**Comment by WilliamIX** [comment]
> Addressing design question 1:
> As a user, if I want to replace a particular species in the CRN, which is present in multiple reactions, then I would expect that species gets changed everywhere. Having multiple 'copies' of the same species is fine, but we need to have a robust updating mechanism that keeps everything in sync.
> Given the 'distributed' nature of the reactions, i.e. they only meet when the CRN object is initialized, I would do the Species consolidation in the CRN initialization.

I like this idea and I think the implementation should be manageable. What we will have to do is go through all the species, merge the ones which are the same, and similarly for all species in all ComplexSpecies and in all reactions (recursively). Does this seem doable? Is a dictionary the correct way to keep track of species or is there a better data-structure?

My other proposed implementation is to do this in the Species constructor (or `__new__` method I have been using) - in particular, we could keep a global dictionary of species and if a new species object is created which already exists, we can just return the existing object.

> On a semi-related note, I'm confused by this `material_type` attribute for Species. What is the purpose of that? It seems to be a species is 'looking' back what higher-level object is created a given species. If it is important, what higher-level object (DNA, promoter, protein) has created a species, then it should be the other way around, for example, a protein is composed of two types a component and a species:
> 
> ```python
> class Protein(Component, Species):
>      def get_species():
>          return self
> ```
> Am I missing something here?

This is a good question - the idea here is that one common naming convention is dna_name, rna_name, protein_name and materialtype_name is a good way to keep track of that. Fundamentally, material_type, name, and attributes are just three elements to identify a species by.

In terms of Components also Being Species - this is an interesting idea which I haven't considered. In my mind, Species are variables which participate in reactions. Components are specifications of functionality. The confusing bit is that you can have multiple Components which are the same internal Species. For example a TranscriptionFactor(species = A) & Phosphoprotein(species=A) is the kind of multi-functionality we want - I'm not sure if this is compatable with Components also BEING species (as opposed to containing species).

**Comment by WilliamIX** [comment]
**Proposed Solution to Design Question 1:**

At compile time, Species are copied and cleaned up so all Species returned in a CRN match (including those inside reactions and inside complexes). This can be done with something like CRN.replace_species. Furthermore, ChemicalReactionNetwork.species[Species] or ChemicalReactionNetwork.species["name"] or ChemicalReactionNetwork.species[index] ways to access the Species in a compiled CRN. This is the same convention proposed to deal with reuse of [Components in Mixtures](https://github.com/BuildACell/BioCRNPyler/issues/123). A similar convention should also be used for Reactions.

**Comment by dr3y** [comment]
Simple solution for ScaffoldSpecies:

`M1 = Species('A')`
`M2 = Species('B')`
`P1 = ScaffoldSpecies([M1,M2])`
`S1 = P1[0]`
`C = Species('C')`
`D = Complex([S1,C])`

then, D is the following:

`D = ScaffoldSpecies([ComplexSpecies([M1,C]),M2])[0]`

notice that D keeps the reference to which position of P1 we are interested in. You then need a way to "dereference" such "monomer" species as well as keeping the knowledge of position and parentage within the "monomer"s.

So they can't be just ComplexSpecies or Species as I've indicated but must be some other class, that knows about being part of a ScaffoldSpecies. However, they must be ALSO Species or ComplexSpecies, otherwise normal mechanisms won't work

**Comment by WilliamIX** [comment]
@dr3y - thanks for the clarification of my long-winded first message. The question is how to do this. `__new__` doesn't seem to be working - so you suggest that we use a function "Complex" to do this, correct?

**Comment by dr3y** [comment]
I think the challenge is to not define new classes to serve as the monomers of the ScaffoldSpecies because then we end up redefining every single "species" branch

**Comment by WilliamIX** [comment]
That is a good point - here is one idea: Make the SubSpecies class inside ScaffoldSpecies be a Species for typing considerations, but also have it contain a Species inside of it which can be any kind of Species. For most purposes, the SubSpecies uses its internal Species. This will also solve the problem of Species being universal - if a Species is changed in a CRN, it will also change the Species contained inside the SubSpecies.

**Comment by dr3y** [comment]
Currently trying a solution where a `Species` is also an `OrderedMonomer` and _CAN_ have a direction, position, and parent. But doesn't start with them. That way you can stick a `Species` into an `OrderedPolymer` (my name for `ScaffoldSpecies`) and it will know what to do.

**Comment by dr3y** [comment]
Update on this: `OrderedMonomer` and `OrderedPolymer` working, but species reference unification has not yet been implemented

**Comment by WilliamIX** [comment]
Find ways to forbid people to change values inside of an object after Compilation. How can we "lock" a CRN?

The use specification is: We should be able to add Species and Add Reactions to a CRN, but not change any Species or Reactions in the CRN. Also cannot CHANGE Species or Reactions inside the CRN once it is compiled - in other words, Species and Reactions should be Locked as well.

@zoltuz

**Comment by WilliamIX** [comment]
Remove Check in CRN.add_species that looks at duplicates - not needed if there is no synchronization.

**Comment by WilliamIX** [comment]
CRN.species will become private with no setter. Getter returns a copy. Same with CRN.reactions. Must add via the add_species and add_reactions function.

**Comment by WilliamIX** [comment]
This issue has been closed - CRN species and reactions are now "local" and copies are returned making them "safe" from unintentional user-meddling.
