### ISSUE TITLE
Make SBML writing annotations for bioscrape toggle-able

### ISSUE THREAD

**Issue by ayush9pandey** [BuildACell/BioCRNPyler#127]
Add 'for_bioscrape' optional keyword argument to `write_sbml_file` function with default False to not write the propensity annotations always.

**Comment by murrayrm** [comment]
I was going to mention that `for_bioscrape` seemed a bit clunky as a keyword.  Given that we may eventually have multiple package-specific annotations for BioCRNpyler functions, perhaps something more general (including even a list) would make sense?  Can be more general than just for SBML output.

**Comment by ayush9pandey** [comment]
Yes, that's a helpful suggestion, will take that into account.

**Comment by zoltuz** [comment]
this feature was added in #103, thanks for suggesting this feature!

**Comment by ayush9pandey** [comment]
Reopening to slightly refactor how it is set up right now after #103. I am changing the behavior a bit so that the higher level functions only see a **kwargs and the `create_kinetic_law` function also remains general in the sense that it doesn't have bioscrape specific things in it. It will call a `create_annotations` function with the **kwargs passed in so that this functionality can be extended in the future. Let me know if you have any thoughts...I will try to make it work this way.

**Comment by zoltuz** [comment]
I agree that's the best way to handle it. In the many merges recently, somehow,  for_bioscrape argument sneaked out of kwargs, it's good to put it back.

**Comment by ayush9pandey** [comment]
Yes, I think it's not out in the open anymore - always carried through kwargs (except in the some of the test code). But due to this move I think something very minor is breaking in #131 ..

**Comment by zoltuz** [comment]
I think PR #131 now solved this
