### ISSUE TITLE
Units in biocrnpyler

### ISSUE THREAD

**Issue by ayush9pandey** [BuildACell/BioCRNPyler#130]
This is an enhancement issue that we should probably work on later. Although bioscrape does not support units and ignores all units. But most other SBML simulators work with units in certain ways. Regardless, the job of biocrnpyler is to create SBML models so we should probably be creating dimensionally correct models too. Towards that end, I think we could have parameter files accept units (if the user desires so)..and then set those units accordingly in our SBML model. Also, we could give options to set the default concentration units for the SBML file. Currently, we set the concentration for species with substance unit = mole, and volume unit = litre (so mole/litre for concentration). 

This issue is also motivated by feedback from some recent users who were wondering what the units are for everything in biocrnpyler.

**Comment by WilliamIX** [comment]
This is a good issue to work on and goes hand-in-hand with some of the Parameter Defaulting schemes I've been thinking about (in particular, when can we "guess a ball-park rate" even if there is no parameter file). It would be ideal if we could re-use someone else's unit conversion library - do you know if libSBML has any support for units?

**Comment by ayush9pandey** [comment]
Writing units in SBML is simple: we already do that a bit when creating SBML files: https://github.com/BuildACell/BioCRNPyler/blob/4c2ec4e6abf54fc9ddc783286b8538f07f882ae8/biocrnpyler/sbmlutil.py#L51

I can work on making sure we have units for all parameters and all initial conditions..

**Comment by WilliamIX** [comment]
This looks like a great package! I think we could even tie it in as an optional dependency. Here is my thought:
1. Have a function inside of the Parameter Class which takes units. These can be read from the parameter files or passed into the Parameter constructor.
2. if Pint is installed, have the ParameterDatabase automatically convert all Parameters to the same units when it returns them. This will mean defining a default set of units (which can be changed, perhaps via a keyword). 
3. If Pint isn't installed or there are no units for a Parameter, everything will be assumed to be the in the default units (current functionality)

**Comment by WilliamIX** [comment]
Add optional units to the parameter objects (and files) which propagates into SBML.

**Comment by ayush9pandey** [comment]
Hard code SBML unit definitions for the following units:
nL, uL, mL, L. NM, uM, mM, M, hour, minute

**Comment by zoltuz** [comment]
#219 solved this
