### ISSUE TITLE
SBML writing of general propensities

### ISSUE THREAD

**Issue by ayush9pandey** [BuildACell/BioCRNPyler#132]
Line 219 of propensities.py says that SBML writing of general propensities is not implemented. I thought that we implemented this earlier. Can you confirm @zoltuz or @WilliamIX  ? I can implement it again if that code got lost somewhere ;)

**Comment by zoltuz** [comment]
As far as I can tell, it wasn't implemented in the previous version either. Here's the corresponding code on the master branch:
https://github.com/BuildACell/BioCRNPyler/blob/master/biocrnpyler/sbmlutil.py#L287

**Comment by ayush9pandey** [comment]
Maybe I got confused with a similar fix in bioscrape...anyways, will add this and test in now

**Comment by zoltuz** [comment]
Thanks! You just need to implement ```_create_kinetic_law()``` function in GeneralPropensity as you see fit.

**Comment by zoltuz** [comment]
I've added the handling of general propensities with all bells and whistles here: https://github.com/ayush9pandey/BioCRNPyler/pull/7

**Comment by zoltuz** [comment]
PR #131 solved this
