### ISSUE TITLE
KineticLaw object not setting correctly for Hill Propensity class

### ISSUE THREAD

**Issue by ayush9pandey** [BuildACell/BioCRNPyler#135]
This is a bug when writing Hill Propensity to SBML, the kinetic law is not written out. 

(Note that this is unrelated to any of the other annotation related bugs - those are now fixed). 

For example: this is how a model looks with a Hill propensity:

![image](https://user-images.githubusercontent.com/8139195/88645719-4d9d5c00-d079-11ea-8455-99d4518cd651.png)

**Comment by zoltuz** [comment]
Thanks for reporting it, I'll check it out

**Comment by ayush9pandey** [comment]
I think I have pin pointed the issue, I'll try to fix it with #131 

The issue here is that the Parameter objects are going to the rate formula as objects and not as values or strings. (BTW, this was also *one of* the issues why annotations were not working)

**Comment by ayush9pandey** [comment]
Is `p.search_key.name` the correct way to find the identifier for a particular object of Parameter class? @zoltuz  / @WilliamIX  ?

**Comment by ayush9pandey** [comment]
I think I'll leave this up to one of you to fix. Here's the issue: 

Currently, the `rate_law` that gets returned looks like: `<Parameter k>*S1^<Parameter n>/(S1^<Parameter n>+<Parameter K>)` 

As you can see, the parameter objects get passed and converted to strings instead of the correct identifier. Due to this reason, SBML does not parse this correctly in the Reaction KineticLaw object.

**Comment by zoltuz** [comment]
> I think I'll leave this up to one of you to fix. Here's the issue:
> 
> Currently, the `rate_law` that gets returned looks like: `<Parameter k>*S1^<Parameter n>/(S1^<Parameter n>+<Parameter K>)`
> 
> As you can see, the parameter objects get passed and converted to strings instead of the correct identifier. Due to this reason, SBML does not parse this correctly in the Reaction KineticLaw object.

I have found the solution here: https://github.com/ayush9pandey/BioCRNPyler/pull/7
<Parameter k> and such is actually libsml Parameter class, not our ```Parameter``` class. 
I've added Parameter.getId() to the appropriate places.

**Comment by zoltuz** [comment]
PR #131 solved this
