### ISSUE TITLE
trigger a warning when multiple species with the same name are written to SBML

### ISSUE THREAD

**Issue by zoltuz** [BuildACell/BioCRNPyler#136]
Trigger a warning if there are multiple species with the same SBML name is added to the SBML model. Not sure how to test for this though. A leftover task from #131.

**Comment by ayush9pandey** [comment]
This is not an issue any more. It probably was an issue at an earlier point of time, but I checked just now by creating a CRN with two species with exactly the same name and only one was added to SBML (so SBML is still valid - no duplication).
