### ISSUE TITLE
DNA construct has introduced a dependancy on matplotlib

### ISSUE THREAD

**Issue by zoltuz** [BuildACell/BioCRNPyler#146]
Hi @dr3y ,

Somehow, I missed that during the review but dna_construct explicitly requires matplotlib (and numpy as well) inside the core code. I have removed numpy already in my version to make the core code numpy (and matplotlib) free, now all the dna_constrct test are broken. 

Can you remove matplotlib or put inside a plotting related function asap? Many thanks!

**Comment by dr3y** [comment]
hi i just submitted a pr #149 to addres this

**Comment by zoltuz** [comment]
resolved in PR #149
