### ISSUE TITLE
merge Enzyme and MultiEnzyme classes

### ISSUE THREAD

**Issue by zoltuz** [BuildACell/BioCRNPyler#148]
We could keep the business logic of ```MultiEnzyme``` and rename it to ```Enzyme```. I don't see a reason to keep both classes. 

Besides, the name is misleading ```MultiEnzyme``` handles multiple substrates and products with a **single** enzyme

**Comment by WilliamIX** [comment]
I am fine with that

**Comment by zoltuz** [comment]
done in #212
