### ISSUE TITLE
Support for Linear vs Plasmid DNA mechanisms

### ISSUE THREAD

**Issue by WilliamIX** [BuildACell/BioCRNPyler#15]
Mechanisms to add: 
Linear DNA should be degraded
GamS degredation inhibition

Should this be done with global mechanisms? Some other way?

**Comment by WilliamIX** [comment]
Note that this can be succinctly modeled in by using attributes and global mechanisms.

**Comment by dr3y** [comment]
circular is an attribute that a `DNA_construct` has, and right now it only affects how we are detecting transcription and translation. `OrderedPolymers` can have attributes but making an `OrderedPolymer` have attribute circular does nothing. What it *should* do though, is make sure that equality between circular constructs works when they are rotated. Likewise, equality of reverse constructs should work.

**Comment by WilliamIX** [comment]
This can just be done via an example notebook with existing mechanisms

**Comment by WilliamIX** [comment]
Do not need to natively support this - can be implemented in 3 lines. Maybe add an example?
