### ISSUE TITLE
sbml error toggle broken in simulate_with_bioscrape_via_sbml

### ISSUE THREAD

**Issue by WilliamIX** [BuildACell/BioCRNPyler#155]
Getting a lot of warnings from bioscrape:

UserWarning: Compartments, UnitDefintions, Events, and some other SBML model components are not recognized by bioscrape. Refer to the bioscrape wiki for more information.
  warnings.warn('Compartments, UnitDefintions, Events, and some other SBML model components are not recognized by bioscrape. ' +

I believe there was a way to toggle these off that was on by default but it doesn't seem to be working now.

**Comment by ayush9pandey** [comment]
Fixed in #158
