### ISSUE TITLE
renderDNA call not compatible with voigt lab's dnaplotlib

### ISSUE THREAD

**Issue by dr3y** [BuildACell/BioCRNPyler#156]
Currently, in plotting.py I use a call to renderDNA which involves the circular= keyword, which is specific to my fork of dnaplotlib (which can be installed by `pip install git+git://github.com/dr3y/dnaplotlib.git@master`) However, it should have a try except statement so that circular= is not fed in if it cannot be.

**Comment by ayush9pandey** [comment]
So, this is fixed now @dr3y  ?

**Comment by dr3y** [comment]
i just tested it it works but there is a small issue with not showing integrase sites. everything else works though

**Comment by dr3y** [comment]
i have noticed a few bugs with the dna construct examples notebook which i will now try to fix

**Comment by ayush9pandey** [comment]
OK! That's fine, I also have a few minor bug fixes that I will push to master with the final stable version 1.0.0. So, I will wait for your bug fix PR then before doing that.

**Comment by dr3y** [comment]
PR #159

**Comment by WilliamIX** [comment]
This is now fixed on master - closing.
