### ISSUE TITLE
How do we want to promote the SBtools slack channel?

### ISSUE THREAD

**Issue by WilliamIX** [BuildACell/BioCRNPyler#165]
Should there be a link on our readme? Should they have to contact one of us to get an invite? @murrayrm what do you think?

**Comment by murrayrm** [comment]
I would be careful about posting anything that allows automatic signup via a publicly accessible site.  It's a good way to get spambots and other things subscribing to the workspace.

I think you can put the link to the Slack workspace in a way in which people who are interested can request being added.  We can then verify they are a real person and add them.

We can also create a link that allows automatic signup that we can send to people who express interest.

**Comment by zoltuz** [comment]
instructions have been added to the README.md how to join to the slack channel. I'm closing this for now.
