### ISSUE TITLE
setup Sphinx to generate the documentation

### ISSUE THREAD

**Issue by zoltuz** [BuildACell/BioCRNPyler#169]
Hi all, 

Here's a suggestion, I'm not super familiar with Sphinx (I never got it to work actually), so I was thinking about an alternative software to automatically generate the documentation. One suggestion would be MkDocs, which works with plain markdown files:
https://www.mkdocs.org/
There's a plug that can generate the documentation from the source code:
https://github.com/pawamoy/mkdocstrings

Let me know what you think!

**Comment by WilliamIX** [comment]
I think taking the path of least resistance here is definitely the best idea! I personally like Markdown a lot - very simple way to get decent formatting. It would be easy to put markdown in a doc string as well if desired.

**Comment by murrayrm** [comment]
Sphinx is pretty standard (eg, used for numpydoc, readthedocs, etc) and supports markdown.  It's what we use for [python-control](https://python-control.readthedocs.io).

**Comment by zoltuz** [comment]
I'll give another try to Sphinx. This looks also interesting: https://blog.jupyter.org/announcing-the-new-jupyter-book-cbf7aa8bc72e

**Comment by ayush9pandey** [comment]
Please keep us updated here (if) how you manage to get it to work! Also, the jupyter books looks cool, but can it be mounted as a reliable webpage ? also, I guess this would not solve the automated documentation generation problem. right?

**Comment by zoltuz** [comment]
Good questions, not sure at the moment about the answers, I'll look into that and update this thread.

**Comment by zoltuz** [comment]
PR #217 has implemented these chagnes. Sphinx generates the documentation by calling `make docs` in the root folder.
