### ISSUE TITLE
Wrong parameter passed into bioscrape annotation. Check images

### ISSUE THREAD

**Issue by ayush9pandey** [BuildACell/BioCRNPyler#174]
Model in SBML:
![image](https://user-images.githubusercontent.com/8139195/91480783-4f189a80-e858-11ea-9c4f-c01383aebd89.png)
Model loaded in bioscrape:
![image](https://user-images.githubusercontent.com/8139195/91480791-517af480-e858-11ea-8d76-e480b2243ecb.png)

Thanks to @Chryron for pointing this out!

**Comment by zoltuz** [comment]
Hi @ayush9pandey, thanks for reporting this. This issue has been solved in PR  #178 (thanks @WilliamIX ) and the dev branch now contains the bugfix.

If you want to give a try, you can install biocrnpyler using the code from the dev branch:
https://github.com/BuildACell/BioCRNPyler/wiki/How-to-install-BioCRNPyler#installing-the-dev-branch
