### ISSUE TITLE
run unit tests without Jupyter notebooks in Travis

### ISSUE THREAD

**Issue by zoltuz** [BuildACell/BioCRNPyler#175]

**Comment by zoltuz** [comment]
A possible solution for this issue: https://stackoverflow.com/questions/32444402/is-there-an-option-for-pytest-to-ignore-the-setup-cfg-file

**Comment by WilliamIX** [comment]
Do we want to do this considering that Travis will soon cost credits and we may be switching to github actions?

**Comment by WilliamIX** [comment]
Unit tests and Combinatorial tests have been factored into two folders, so it is easy to choose which to run. Additionally, all Jupyter tests are now skipped if Jupyter is not installed.
