### ISSUE TITLE
Can't pretty print GeneralPropensity

### ISSUE THREAD

**Issue by mkapasiawala** [BuildACell/BioCRNPyler#179]
Trying to pretty print a CRN with a custom mechanism with GeneralPropensity for propensity_type leads to the error "class Propensity is meant to be subclassed!" To be clear, I am using GeneralPropensity, not propensity. There doesn't seem to be a way to pretty print with GeneralPropensity, so maybe that's why it's defaulting to Propensity?

**Comment by ayush9pandey** [comment]
Yes, I think this needs to be fixed - the general propensity class is missing the pretty print function. Thanks for pointing it out.

**Comment by zoltuz** [comment]
Hi @mkapasiawala, thanks for reporting this. This issue has been solved in PR #178 (thanks @WilliamIX!) and the dev branch now contains the bugfix.

If you want to give a try, you can install biocrnpyler using the code from the dev branch:
https://github.com/BuildACell/BioCRNPyler/wiki/How-to-install-BioCRNPyler#installing-the-dev-branch
