### ISSUE TITLE
Link to documentation in ReadMe useful?

### ISSUE THREAD

**Issue by hainesm6** [BuildACell/BioCRNPyler#181]
# issue

In the ReadMe, there's this [link](https://readthedocs.org/projects/biocrnpyler/) to a `readthedocs` page which doesn't contain much material.

# possible solution

`Remove the link` and have new users visit the [website](http://buildacell.io/BioCRNPyler/#/) instead which has further links to Jupyter nbs for getting started. If this functionality is something you want to include in future you could add it as an `enhancement issue` for someone to work on.

**Comment by ayush9pandey** [comment]
Thanks for the suggestion! I believe @zoltuz  decided (#169)  to give Sphinx another try that would set up the readthedocs documentation page and serve as the webpage for the toolbox as well.

**Comment by zoltuz** [comment]
Thanks for pointing that out, we will have the docs up and running soon. Until then check out the example folder: https://github.com/BuildACell/BioCRNPyler/tree/master/examples

**Comment by ayush9pandey** [comment]
For now, I have removed the link and added a " Coming Soon message". Fixed in dev branch.
