### ISSUE TITLE
Roadrunner as an "extra" dependency requirement

### ISSUE THREAD

**Issue by ayush9pandey** [BuildACell/BioCRNPyler#196]
How do we feel about having libroadrunner as an extra dependency that gets installed with `pip install biocrnpyler[all]` . Since, this is a plotting library it would make sense to include this with the other plotting libraries networkx, and fa2 as the extra dependencies.

**Comment by zoltuz** [comment]
Hi Ayush, 
I was thinking about this on the other day and came to the same conclusion. My rationale was ```pip install biocrnpyler[all]``` means all dependencies. 
An alternative would be ```pip install biocrnpyler[simulators]```, which installs libroadrunner (and bioscrape in the future)

**Comment by ayush9pandey** [comment]
Yeah, if we wanna go that route, we could have "all" get literally all dependencies and then "plotting" gets the only the plotting ones and "simulators" gets the simulators to provide all options? Doesn't hurt I guess..

**Comment by WilliamIX** [comment]
Go for it if you want!
