### ISSUE TITLE
"nbval" should be automatically installed as a prereq for testing

### ISSUE THREAD

**Issue by WilliamIX** [BuildACell/BioCRNPyler#232]
This is a pytest addon.

**Comment by zoltuz** [comment]
By default, nbval is installed as part of the test suite:
https://github.com/BuildACell/BioCRNPyler/blob/c3ca0ae3138bec2b3addde7ac44581285c1b4b5a/setup.py#L39
Did you face an issue running the test suite?  (`pytest .` or `python setup.py test`)

**Comment by WilliamIX** [comment]
`python setup.py test` works just fine. 

The issue is that when installing the software from PIP (or github) nbval does not seem to install automatically (on my local machine) except in the context of the test suite. For example, if I `pip install biocrnpyler[all]` it does not get all the dependencies so I can run individual tests. For context, my hacky way of getting biocrnpyler set up on a new computer (my old one got decapitated) was to pip install it to get the dependencies, then uninstall it and work from a clone of the github repository.

**Comment by zoltuz** [comment]
I see! 
`pip install biocrnpyler[all]` meant for the end-users, they hardly ever want to run tests. 
If you call `python setup.py test` for the first time, then it will install all the necessary packages that are needed for testing. Alternatively, we could create a `requirements_dev.txt` that contains all the necessary packages for a developers.

**Comment by WilliamIX** [comment]
I like the` requirements_dev.txt `idea! We should be able to set up a `pip install biocrnpyler[dev]` somehow as well, right? Or is `[all]` special and hardcoded into pip?

Relatedly - we would want to put all the examples and tests into the dev distribution, right?

@ayush9pandey any thoughts on this?

**Comment by zoltuz** [comment]
I like the `pip install biocrnpyler[dev]` idea because all of the installation-related info would be in one place (i.e. in `setup.py`)

Based on this:
https://github.com/BuildACell/BioCRNPyler/blob/c3ca0ae3138bec2b3addde7ac44581285c1b4b5a/setup.py#L27

Something like this would work:
```python
    extras_require = { 
        "all": [
            "numpy",
            "matplotlib",
            "networkx",
            "bokeh>=1.4.0",
            "fa2"
            ],
       "dev": [
           "pytest",
           "pytest-cov",
           "nbval"
        ],
        },
```

**Comment by WilliamIX** [comment]
Great - I will do that in a PR soon. A couple follow up questions:
1. I guess we should now include all the examples in the manifest.ini (unless there is a way to make a seperate manifest included as an extra?]?
2. Do we want to make Bioscrape included in dev as well now that it is Pip installable? What I am getting at is it would be great if the pip install could easily have all the example notebooks work.... maybe we want a third option [examples]?

**Comment by ayush9pandey** [comment]
I also like the [dev] install idea. Although in Zoltan's code above for dev "numpy", "matplotlib" etc.. will not be installed. 

For the simulators - I think we can include bioscrape and roadrunner in the "all" keyword. So, if someone does pip install biocrnpyler[all] they literally get all dependencies. Creating another keyword like "simulator" might get too complicated for installation process. For end-user keeping it to two options seems good - you either install the basics or you install "all".

**Comment by WilliamIX** [comment]
nbval has now been removed, because it broke. closing this issue.
