### ISSUE TITLE
PrettyPrint has the wrong equation 

### ISSUE THREAD

**Issue by zjuradoq** [BuildACell/BioCRNPyler#235]
This is a minor issue but noticed it while writing. The rate formula is correct but the pretty print equation has a misplaced parenthesis. (1+s1/K)**n vs 1+(s1/K)**n

https://github.com/BuildACell/BioCRNPyler/blob/c3ca0ae3138bec2b3addde7ac44581285c1b4b5a/biocrnpyler/propensities.py#L521

**Comment by zoltuz** [comment]
Thanks for reporting this. I'll take care of it asap.

**Comment by zoltuz** [comment]
Hi @zjuradoq ,
Thanks for pointing this typo out! This part of the code has been overhauled in the latest version (still in development). You can have look here:
https://github.com/BuildACell/BioCRNPyler/blob/dev/biocrnpyler/propensities.py
If you want to give it a try, you can install the latest version by following the steps here:
https://github.com/BuildACell/BioCRNPyler/wiki/How-to-install-BioCRNPyler#installing-the-dev-branch-on-github

Let me know if you have any other questions/concerns!

Zoltan
