### ISSUE TITLE
"Empty or Extinction" Species

### ISSUE THREAD

**Issue by lingxincheng08** [BuildACell/bioCRNpyler#269]
Is there a way to create an "empty species"? In mathematical biology sometimes we need an empty set in the network, it kind of represents "extinction", or it is like sometimes we just observe one region and then we have animals(or other things) come and go, therefore need an empty set to represent the running away event. Thanks!

**Comment by ayush9pandey** [comment]
You can have reactions with empty reactants or products. Essentially, the reaction tuple can look like:

`r1 = Reaction([species_A], [ ], propensity_type = your_propensity_object)`
or for mass action
`r1 = Reaction.from_massaction([species_A], [ ], k_forward = k1)`

for a reaction that models species_A -> nothing.

**Comment by WilliamIX** [comment]
This is a non-issue. Closing.
