### ISSUE TITLE
Problem with add_attribute() in Component class

### ISSUE THREAD

**Issue by zoltuz** [BuildACell/BioCRNPyler#43]
Hi, 

There's a set_attribute method in Component that has a runtime error problem. MWE:

```
from biocrnpyler import Component
comp_name = 'test_component'
parameters = {"mock_param": 1}
component = Component(name=comp_name, mechanisms={}, parameters=parameters, parameter_file=None, mixture=None, attributes=[], initial_conc=0, parameter_warnings=True)
component.add_attribute('ee')
```
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/Users/zoltuz/PycharmProjects/biocrnplyler/biocrnpyler/component.py", line 101, in add_attribute
    self.species.add_attribute(attribute)
AttributeError: 'Component' object has no attribute 'species'

Do we need this method? It seems that way there's no species variable in Component at all.

Cheers,
Zoltan

**Comment by WilliamIX** [comment]
Yes, we can get rid of this - legacy idea that I never ended up using.

**Comment by zoltuz** [comment]
For now, I've added a if test around it so if `add_attribute()` called when `self.species is None` then it generates a warning. 
Updated the corresponding unit test as well.  

If the whole attribute idea is not in use anymore, then we can pull the plug on it.

**Comment by WilliamIX** [comment]
Also, I figured out the use-case for why I added this feature. It is so you can do "attribute" based rules in reaction schemas. In other words, a mechanism schema could effect every species with a given attribute. I used it in the global dilutions example. I think we should keep it as a feature.

**Comment by WilliamIX** [comment]
It sounds like this error is fixed - so I am closing the issue.
