### ISSUE TITLE
parameter update in Component class

### ISSUE THREAD

**Issue by zoltuz** [BuildACell/BioCRNPyler#44]
Hey,

Inside Component class there is an update_parameters() method with this code

```
   def update_parameters(self, mixture_parameters = {}, parameters = {},
                          overwrite_custom_parameters = True):
        for p in parameters:
            if overwrite_custom_parameters or p not in self.custom_parameters:
                self.parameters[p] = parameters[p]
                if p in self.custom_parameters:
                    self.custom_parameters[p] = parameters[p]

        for p in mixture_parameters:
            if p not in self.parameters:
                self.parameters[p] = mixture_parameters[p] 
```
Do I understand correctly, we only update custom parameters, if they already exist in the dictionary with the same key? 

Zoltan

**Comment by WilliamIX** [comment]
Yes - the idea is that parameters are automatically inherited from the mixture unless they are overwritten explicitly by the user as custom parameters. Does that make sense (and is it the right way to do things?)

**Comment by murrayrm** [comment]
Is there a reason not to just say
```
local_parameters = dict(self.parameters)  # make a copy
local_parameters.update(parameters)       # overwrite with users-specified parameters
```
or something similar?  The use of `for` loops is not particularly Pythonic.

**Comment by WilliamIX** [comment]
Unfortunately Richard's solution, although simpler, doesn't quite capture the logic I want.

update_parameters has multiple use cases.
1. being called by a mixture with no custom parameters in which case parameters.update(mixture_parameters) would work.
2. being called by a mixture with custom parameters in which case
parameters.update(mixture_parameters)
parameters.update(custom_parameters)
3. being called to update local parameters not from a mixture:
In this case, parameters.update(mixture_parameters) will overwrite the existing parameters with an empty dictionary which won't work if this function is called directly to pass in parameters to a Component not from a mixture.

There is probably a way to get the loops out of here, but I don't immediately see it. I am commenting the code to explain the logic better (which will be pushed to master soon) and closing the issue for now unless one of you has an explicit solution.
