### ISSUE TITLE
Error in component.py line 102 - Instance of 'Component' has no 'species' member

### ISSUE THREAD

**Issue by ayush9pandey** [BuildACell/BioCRNPyler#48]

**Comment by zoltuz** [comment]
I think, this is the same as #43, but how did you invoke this error?

**Comment by ayush9pandey** [comment]
I think that part of the code is unreachable at the moment, so the error is not invoked in any of the tests.

**Comment by WilliamIX** [comment]
This is the same as #43 and has been fixed.
