### ISSUE TITLE
Error when I tested all examples in advanced examples ipython notebook

### ISSUE THREAD

**Issue by WilliamIX** [BuildACell/BioCRNPyler#53]
Tested all the examples - getting an error in the last part of the advanced ipython guide: "myMixture.RNAase.add_attribute("machinery")" throws "AttributeError: 'BasicExtract' object has no attribute 'RNAase'"

**Comment by ayush9pandey** [comment]
Yeah, that is from my commit. I changed `RNAase` Component in a Mixture to `rnaase` all in small alphabet because that is how it was for RNAP -> rnap and ribosome. Changing to `rnaase` fixes the issue. I changed this at other places but forgot to change the notebook.

**Comment by murrayrm** [comment]
I'm also getting an error, but right at the start.   In the first example, I get the following error
```
IndexError                                Traceback (most recent call last)
<ipython-input-1-170dd96745ca> in <module>
     60 
     61         results = myCRN.simulate_with_bioscrape(timepoints, x0_dict, stochastic = stochastic)
---> 62         plt.plot(timepoints, results["protein_ref"], label = "Load = "+str(dna_Load))
     63 
     64     plt.xlim(0, 5)

IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices
```
I *think* I am running the latest version of `biocrynpyler`, `bioscrape`, `subsbml`, etc.  Any hints?

**Comment by ayush9pandey** [comment]
`results` should be a Pandas DataFrame type. If it's an array then it might be some issue with your `bioscrape` installation?

**Comment by murrayrm** [comment]
Thanks @ayush9pandey.  Where is the master copy of `bioscrape`?

**Comment by ayush9pandey** [comment]
We updated the master branch of `bioscrape` just this week, so it should have all the updates. Can you try reinstalling bioscrape form - https://github.com/ananswam/bioscrape/

**Comment by murrayrm** [comment]
That's what I'm using.  I've done a `git clone` of `https://github.com/ananswam/bioscrape/`.  Log shows that the last commit was 2f9adcd0 with message "moving working examples" on 14 Aug.  Look right?

**Comment by murrayrm** [comment]
Oops, that's not right.   Last commit was 570e95d on 13 Aug with message  "bioscrape.inference package working version 0.1".

**Comment by ayush9pandey** [comment]
Yes, that's correct. Not sure why you are getting that error then. I tried installing it again on my machine and I get `results` from a bioscrape simulation as a Pandas DataFrame. Maybe you can try deleting the installed package from `site-packages` and then reinstall?

**Comment by murrayrm** [comment]
I get the same type of error when I run`Basic Examples - START HERE` in bioscrape/.  ??

**Comment by murrayrm** [comment]
Removed and reinsintalled; same error.

Is there a version number or something I can check in `bioscrape` to make sure I have the right version?

**Comment by murrayrm** [comment]
Looks like the problem may be that pandas was not installed.  Working on it.

**Comment by ayush9pandey** [comment]
Yeah, it should be that. I found out that although bioscrape imports Pandas with a `try` `except` block every time but at some places either a warning is not printed (on catching an exception) and at some other places if Pandas can't be imported, the old return method is being used (that returns an array).

**Comment by murrayrm** [comment]
OK, fixed my problem.  Sorry for the  false alarm.

Getting the same error as @WilliamIX now.

**Comment by WilliamIX** [comment]
This is fixed - the name was changed from RNAase to rnaase.
