### ISSUE TITLE
When creating reactions with a propensity_params dict, a rate "k" should not be required in the constructor.

### ISSUE THREAD

**Issue by sclamons** [BuildACell/BioCRNPyler#54]
the rate k should be able to be in the propensity_params dict, so that all the params can be grouped.

**Comment by ayush9pandey** [comment]
I agree. Similar to #57 and a similar issue in bioscrape, it is not making very much sense to me why the "k" is required in the constructor.

**Comment by WilliamIX** [comment]
This is fixed.
