### ISSUE TITLE
Design Question: BioCRNpyler Parameter Inference With Bioscrape

### ISSUE THREAD

**Issue by WilliamIX** [BuildACell/BioCRNPyler#55]
Consider the pipeline where biopcrynpyler is used to construct a variety of models, which are then sent to bioscrape for PID. In it's current form, biocrnpyler assumes all rate constants are *numerical* values, including for more advanced propensities types like hill functions which are automatically looked up in a variety of parameter tables. However, bioscrape wants these parameters to be *variables* with names as well as values in order to quickly change them throughout a param ID run. How do we reconcile these two approaches? What do we need to consider in this pipeline? Feedback appreciated @murrayrm  @ayush9pandey @zoltuz 

My thoughts:
- use biocrnpyler's parameter naming convention (used to load parameter files) to automatically name all of its internal variables whenever a bioscrape model is created and set the initial values from the biocrnpyler config file.
- - Allow for manual override of this naming convention.
- - Should all parameters be named similarly when saving as SBML?

**Comment by murrayrm** [comment]
I'm assuming PID is "parameter ID" (versus proportional-integral-derivative, which is more common).

Your approach sounds reasonable, especially using the numerical values as initial values.  

I think you have to be careful that the name created for the variable is unique.  At the least, you may want to come up with some naming convention so that you can differentiate between variables that might have the same names but coming from different components.

**Comment by ayush9pandey** [comment]
I am a bit confused here. Are we creating bioscrape models directly from biocrnpyler? My understanding was that biocrnpyler would be a tool to quickly create commonly used circuit models and output as SBML. 

If that's correct, then to generate a valid SBML model all parameters have ids and values. Also, all ids have to be unique (addressing Richard's comment above)  -- these are things that we have already implemented in biocrnpyler. 

With regards to parameter id, if you are loading an SBML model into bioscrape for identification, then all parameters have values and associated unique ids (also names). 

If not and you want a new "feature" in biocrnpyler that connects to bioscrape for parameter id, then your approach makes sense to me as well. However, I'd be interested in understanding how much would we be saving on computational time by going by this route and skipping the SBML writing and loading steps.

**Comment by WilliamIX** [comment]
The main use of biocrnpyler is to generate SBML models; when it does this I believe all parameters are currently local and called "k". I also added ability for biocrnpyler to directly create bioscrape models, not through SBML. This allows for direct use of built-in-propensity types resulting in up to a 3x speedup. Once Biocrnpyler exports a bioscrape model, it is very easy to use bioscrape's tools to do parameter identification. The catch is that figuring out which parameters are which is a pain in the butt currently (and similarly for SBML models) hence the question of whether we want to institute a parameter naming convention. I am hoping to use biocrnpyler with bioscrapes parameter ID features, so I'd like to make this pipeline easy and transparent.

**Comment by ayush9pandey** [comment]
Got it.

As you mentioned, taking names from the config files and using those names in the SBML and bioscrape models both should work (and is a better approach too, than just using "k" every time).

**Comment by DIEGOA363** [comment]
What's the status of this?  I'd like to generate models with biocrnpyler and  do simulations/parameter sweeps with other packages than bioscrape. I have been doing somethings like this in my own package:

```python
# 'parameters' is a list with all the parameter names in the order they were added to the SBML model
# 'new_parameters' is a dictionary with new values
# loop through all local parameters in the SBML model
for rxn_id, rxn in enumerate(sbml.getListOfReactions()):
    for param_id, param in enumerate(rxn.getKineticLaw().getListOfParameters()):
        param.setValue(new_parameters[parameters[rxn_id][param_id]])
```

If you've decided on a naming convention I'd be happy to try implementing it as right now it's the main deterrent from switching over to biocrnpyler.

**Comment by WilliamIX** [comment]
If you use biocrnpyler to generate an SBML model, you can do whatever you want with it in terms of other packages and use code similar to what you are showing above. Currently all parameters are stored as local variables inside kinetic laws in biocrnpyler models. 

Parameters do have an internal naming convention, as described at the top of the parameter.py file and in the parameter loading ipython notebook. However, this convention is not used to save parameter names in SBML as you probably have noticed.

I think that pushing this naming convention into SBML writing is a great idea. Here is a possible work flow of how this could work (but not necessarily the best way - @ayush9pandey  @zoltuz  what do you guys think of my suggestions below?):
**Goal: Store parameters names in the SBML File in smarter ways so parameter inference is easy.**

1. Allow the Component.get_parameter(..) function to return a tuple: (param val, param name). 

2. Allow the Reaction constructor (Reaction. _ _ init _ _ ) to take rate parameters in either of two forms [in total this will mean changing how k, k_rev, and elements of the parameter_dictionary {param_name: k} are evaluated]:
     Form 1: a single value to preserve simple creation of reactions from numerical parameters.
     Form 2:  (float, name_tuple).  In this case, the reaction should save all of its parameter names.

3. When calling ChemicalReactionNetwork.generate_sbml_model(...) have an options keyword for two options:
     Option 1: All parameters are local to the KineticLaw. This makes every parameter unique and is useful for doing inference on single parameters at a time. Note that currently parameter names and IDs are all things like "k", "K", "n", etc. and are just stored as local variables in each SBML KineticLaw. In effect, it would be good for this behavior to remain mostly unchanged.
     Option 2: All parameters are global SBML parameters and use names based upon the parameter 
naming convention key tuple that produced the parameter. This allows for parameters to be shared between multiple reactions or unique to a given reaction depending on their name. This is useful if you want to do inference on a parameter that might govern multiple rates.

4. When generating an SBML model, the function sbmlutil.add_reaction(...) needs to take a new (optional) set of parameter names which it can then use to name the parameters as described above when adding an SBML reaction.

@DIEGOA363 let me know what you think of this approach and if it would work with the software workflow you are currently building - in general, I think it's a great addition to the software and will definitely get you up to speed on how the nuts and bolts of BioCRNpyler work. As you begin working deep in the code, please keep the following in mind as well. A) Always work in your own development branch. Then to merge branches, first merge master into your branch then ensure all tests run and  all example ipython notebooks run before making a merge request. B) Please comment your code clearly and produce an example jupyter notebook testing all aspects of your code and describing functionality. C) Because this code would add fairly deep changes to the software, it would be to great to produce a set of unit tests like those in the Tests folder. Happy to discuss any of these details with you if you want further clarification.

**Comment by WilliamIX** [comment]
@DIEGOA363 these changes have been implemented into the Dev branch if you want to try it out. The basic idea is that a parameter's SBML name is: "ParameterName_PartID_Mechanism". If PartID is None or Mechanism is None, those elements disappear, but the underscores stay (kind of an SBML hack to make sure the parameters Name = K, PartID = A and Name = K, Mechanism=A have different string names).

**Comment by WilliamIX** [comment]
This issue is closed now that BioCRNpyler parameters reliably become well-defined SBML parameters that can be accessed directly by other software. Lets get some pipelines going!
