### ISSUE TITLE
Inconsistent use of "k" in Reactions with "general" mechanism type

### ISSUE THREAD

**Issue by sclamons** [BuildACell/BioCRNPyler#57]
When a Reaction is created using the "general" mechanism type, it is still required to have a _k_  base propensity. _k_ is shown in the string representation of the Reaction, but is _not_ used by bioscrape.

Example:
```
P = Species(name = "P", material_type = "protein")
params = {"rate": "10"}
prod_rxn = Reaction([], [P], propensity_type = "general", k = 0.5, propensity_params = params)
deg_rxn  = Reaction([P], [], k = 1)
dummy_CRN = ChemicalReactionNetwork([P], [prod_rxn, deg_rxn])
print(dummy_CRN)
```

gives

```
Species = protein_P
Reactions = [
	 --> protein_P        general: k(x)=0.5*10
	protein_P -->         massaction: k_f=1
]
```

but when run with bioscrape (deterministically), it goes to steady state 10 instead of 5:

```
timepoints = np.linspace(0, 2000, 1800)
x0_dict = {}
results = dummy_CRN.simulate_with_bioscrape(timepoints, x0_dict, stochastic = False)
results['protein_P'].max()
```
```
10.000000003174144
```

**Comment by ayush9pandey** [comment]
I agree, the use of "k" in reactions with "general" propensity type doesn't make much sense. 

Another issue similar to this that I just created - https://github.com/ananswam/bioscrape/issues/39

**Comment by WilliamIX** [comment]
Non-massaction propensities no longer require the parameter k.
