### ISSUE TITLE
Add a helper function to type check species' for mechanism and component classes.

### ISSUE THREAD

**Issue by WilliamIX** [BuildACell/BioCRNPyler#59]
Code like the following should be more automated:

if isinstance(rnap, Species):
            self.rnap = rnap
        #or is type string, in which case create a 
        elif isinstance(rnap, str):
            self.rnap = Species(name = rnap, material_type = "protein")
        #someone might make RNAP a component if they want to add it to a mixture, as you might with a T7 polymerase in a cell-free system
        elif isinstance(rnap, Component) and rnap.get_species() != None:
            self.rnap = rnap.get_species()
        else:
            raise ValueError("'rnap' parameter must be a string, a Component with defined get_specie(), or a chemical_reaction_network.specie")

**Comment by zoltuz** [comment]
I agree. David Beazley has an excellent talk on this: https://forum.dabeaz.com/t/the-fun-of-reinvention-pycon-israel-june-12-2017/204
Below the talk in the forum, there are some packages mentioned, but none of them is maintained at the moment. 
But I guess we can implement a basic type checker using type hints (just like in the video).

**Comment by WilliamIX** [comment]
functions have been added to Mixture and Component.
