### ISSUE TITLE
Testcase not triggered

### ISSUE THREAD

**Issue by zoltuz** [BuildACell/BioCRNPyler#63]
Hi William, 

This test is not being triggered:
```python
    def test_reaction_initialization(self):
        from biocrnpyler import Reaction

        with self.assertWarns(Warning):
            Reaction(inputs=[], outputs=[], k=0.1, propensity_type="massaction", propensity_params=None)
```
It **doesn't** generate a warning, when I create the object with this signature.
in this file
[test_reaction](https://github.com/BuildACell/BioCRNPyler/blob/master/Tests/test_reaction.py
)
Could you have a look? Many thanks!

**Comment by WilliamIX** [comment]
@zoltuz could you please add better documentation (like a testing readme) so I can know how to make new tests? was looking at this before and I just don't understand how it works. Also the tests you made are completely uncommented so I don't know what they are testing for and what to fix when they break.

**Comment by zoltuz** [comment]
I'm sorry to hear that! I'm going to make sure the test cases are better documented.

 Generally speaking, each test case probes an internal mechanism of a given object (e.g. it still triggers an exception if one gives a non-exiting filename as an argument to the object, etc). 

I'm going to comment out the failing test, for now, just to stop Travis complaining about it.

**Comment by WilliamIX** [comment]
Okay, I will close the issue. In the near future, I plan a bunch of new tests.
