### ISSUE TITLE
complex order matters

### ISSUE THREAD

**Issue by dr3y** [BuildACell/BioCRNPyler#65]
when using `mechanism.update_species(complex,species)` you don't get the same result as doing `mechanism.update_species(species,complex)`. Should it be the same? It would be useful either way.

Also, making a complex with more than two species yields multiple "complex_complex_complex..." in the representation.

**Comment by lianamerk** [comment]
It would be helpful to have an "ordered = True/False" option for complex creation, where you can specify a given order (i.e. if binding reactions must be sequential)

**Comment by WilliamIX** [comment]
There are now 3 subclasses of Species, ComplexSpecies (unordered lists of Species), OrderedComplexSpecies(ordered list of species) and Multimer (multiset of a single species).
