### ISSUE TITLE
Detailed E. coli growth model

### ISSUE THREAD

**Issue by sclamons** [BuildACell/BioCRNPyler#66]
Might be useful to have a module for E. coli growth and basic cell resources along the lines of https://www.ncbi.nlm.nih.gov/pmc/articles/PMC372817/pdf/microrev00033-0134.pdf ("Growth Rate of E. coli", Allen G. Marr, 1991). Model includes free amino acid, total protein, ribosome, charged and uncharged tRNA, and ppGpp (a signal molecule used to monitor charged/uncharged tRNA). Provides nice, quantitative coupling between cell resources and growth rate.

**Comment by WilliamIX** [comment]
TxTlDilutionMixture now somewhat serves this purpose. It doe snot include amino acids or tRNA. However it does include RNAase, RNAP, and Ribosomes with loading effects. Additionally, there is a background gene that transcribes and translates at a constant background rate to simulate the core housekeeping of E coli. Parameters are ballparks at best.

Definitely room for improvements including sigma factors, plasmids, tRNAs, etc.

**Comment by WilliamIX** [comment]
This issue will hopefully be solved by integrating BioCRNpyler into a simulator with a notion of growth. Stay tuned!
