### ISSUE TITLE
Cooperativity parameter matters for update_reactions but not for update_species

### ISSUE THREAD

**Issue by dr3y** [BuildACell/BioCRNPyler#67]
I'm looking at the `One_Step_Cooperative_Binding(Mechanism)` mechanism, and I can see that in `update_reactions()` the default value of `cooperativity` is `None`, but in `update_species` the default value is `1`. This creates the wrong species for the reactions if you want to change the cooperativity in the component rather than in the mechanism.

**Comment by WilliamIX** [comment]
Fixed and pushed to master. Thanks for catching this
