### ISSUE TITLE
pretty_print functions for species, reactions, and CRNs

### ISSUE THREAD

**Issue by WilliamIX** [BuildACell/BioCRNPyler#71]
This function should make it easier to understand chemical species, in particular complexes and subcomplexes.

It should also make it easier to understand reactions, perhaps making rate functions optional.

All this should be added together to make pretty representations of CRNS.

**Comment by dr3y** [comment]
I am particularly interested in a good representation of the heirarchical nature of complexes. For example, right now it's hard to tell between ComplexSpecies([Multimer(s1,2),s2]) and ComplexSpecies([s1,s1,s2]). But it should be like complex_(2xprotein_s1)_protein_s2 vs complex_2xprotein_s1_protein_s2

**Comment by WilliamIX** [comment]
@dr3y see the .pretty_print(...) function for ChemicalReactionNetworks, Reactions, and Species. Examples are now in the advanced examples notebook (see the first example). Feel free to improve these functions as needed, especially in terms of adding additional printing options. Unlike repr, it is not used internally for any purpose other than display so that leaves lots of room for improved printing etc.

**Comment by WilliamIX** [comment]
These have been implemented.
