### ISSUE TITLE
Typo in Developer Overview Notebook

### ISSUE THREAD

**Issue by AnkitaRoychoudhury** [BuildACell/BioCRNPyler#75]
Hi! In the Developer Overview notebook under creating a custom component, I think there is a typo in the constructor. It should say 

if isinstance(product, Species):
            self.product = product

instead of 
if isinstance(product, Species):
            self.product = dna_name

Am I correct?

**Comment by WilliamIX** [comment]
We want the product to be a Species, so I think you are correct. I update the notebook. Please let me know if you find any more inconsistencies.

Additionally, there is now a nice helper function that takes care of this logic automatically:
    for any Component you can write:
    self.internal_species = self.set_species(species, ....)
which will automatically test if a species is a string, Component, or Species and take care of everything else.
