### ISSUE TITLE
Add easier constructors for non-mass action propensity types

### ISSUE THREAD

**Issue by WilliamIX** [BuildACell/BioCRNPyler#81]
Just a thought, but we could have functions like PositiveHillReaction which are just wrappers around Reaction to make it easier to instantiate things without dictionaries.

It would also be cool if we could use species like A+3B >> C+2D with defined operators "+", "*" and ">>" to create reactions.

**Comment by WilliamIX** [comment]
Idea: make different reaction types different classes. This will require more work, but is conceptually a lot cleaner. 

To keep backwards compatibility, keep Reaction(...) as a helper function which produces reactions of different types. Use a different name for the base-class of different reaction types, like reaction() [which will never be used anyways - it will always be subclassed]. 

Code areas that likely need revision:
2. SBML writing
3. Example notebooks.

**Comment by zoltuz** [comment]
update: PR #103 works on this issue.

**Comment by zoltuz** [comment]
PR #103  added this functionality!  Thanks for the discussion!
