### ISSUE TITLE
Refactoring some files

### ISSUE THREAD

**Issue by WilliamIX** [BuildACell/BioCRNPyler#86]
I think we need to refactor the code (and examples) to make everything more organized and keep out mutual dependence on imports (which is sometimes a problem). Here is my proposed refactoring:

Core files which will stay the same: chemical_reaction_network.py, mixture.py, sbmlutil.py, plotting.py, parameter.py

Other files will be refactored into simpler subfiles that are organized by topic:
1. mechanism.py --> mechanism.py [containing just the Mechanism] + enzyme_mechanisms.py, binding_mechanisms.py, txtl_mechanisms, etc.
2. dna_assembly.py --> dna_assembly [containing the core class] + new files: promoters.py, ribosome_binding_sites.py...etc.
3. component.py --> component.py [containing only the core Component class], basic_component.py [Contains type classes like DNA, RNA, Protein, ChemicalComplex]. Very specific Components like dCas9 can have their own file.

@zoltuz @ayush9pandey @dr3y do you guys have any thoughts on this? My one concern is breaking people's existing code. Is there a way to make sure that current import paths still work as expected for back-comparability when/if I do this?

**Comment by murrayrm** [comment]
Some good guidelines here: https://docs.python-guide.org/writing/structure/

**Comment by dr3y** [comment]
usually i import biocrnpyler and everything is called in. So if it works like that then it shouldn't be a problem? I think it's because it says from xxx import * in the __init__?

**Comment by murrayrm** [comment]
You can definitely use `__init__.py` to make sure that `import biocrynpyler` or `from biocrnpyler import *` works as expected.

**Comment by WilliamIX** [comment]
This has now happened in the master branch.
