### ISSUE TITLE
Specifying part_id in Reversible_Bimolecular_Binding (Mechanism)

### ISSUE THREAD

**Issue by mkapasiawala** [BuildACell/BioCRNPyler#88]
If you look at line 328 of mechanism.py, it seems like it should say `part_id = repr(s1)+"-"+repr(s2)`
rather than `repr(s1)+"-"+repr(s2)`. Otherwise if part_id is None, then it remains None and doesn't get updated.

**Comment by WilliamIX** [comment]
This has been fixed in the newest WPDev merge to master.
