### ISSUE TITLE
Material type inheritance for complexes

### ISSUE THREAD

**Issue by mkratz** [BuildACell/BioCRNPyler#92]
When applying a filter for dilution and degredation, it seems that ComplexSpecies() objects will inherit the material types of both their parent species. 

For instance, if we create an object, ComplexSpecies([RBZ,mRNA])  and set dilution to True for RBZ, mRNA and set mRNA degredation to True, the resulting Complex will be both degraded and diluted. If we look at the source code (global_mechanism.py) we see why, for applying dilution and degredation for ComplexSpecies objects, apply_filter() will look at the species that make up the object.  Further, this results in conflicting degredation conditions results in an error e.g. Complex to False and RBZ or mRNA to True. 

Ideally, this would be a decision the user could make on their own i.e. should dilution be applied based on ONLY complex material_type or based of all constituent material types through some kwarg. 

I've attached a parameter txt and a code txt (just rename file extension to ipynb) which demonstrates this issue. 
[GHI_Demo.txt](https://github.com/BuildACell/BioCRNPyler/files/4762085/GHI_Demo.txt)
[params.txt](https://github.com/BuildACell/BioCRNPyler/files/4762086/params.txt)

**Comment by zoltuz** [comment]
I could reproduce the error based on the example file. Thanks for sending it @mkratz

**Comment by WilliamIX** [comment]
This will be fixed in my newest PR (which initially will go to the dev branch) and then be fixed in the next merging of dev into master at the end of the month.

**Comment by zoltuz** [comment]
I've checked the example attached to this issue with the code in #119, it no longer gives an error.

**Comment by zoltuz** [comment]
Hi @mkratz,  thanks for reporting this. This issue has been solved (thanks @WilliamIX! ) and the dev branch now contains the bugfix.

If you want to give a try, you can install biocrnpyler using the code from the dev branch:
https://github.com/BuildACell/BioCRNPyler/wiki/How-to-install-BioCRNPyler#installing-the-dev-branch
