### ISSUE TITLE
Conditional Bioscrape for Tests

### ISSUE THREAD

**Issue by WilliamIX** [BuildACell/BioCRNPyler#95]
@zoltuz 

Would the following work to make tests run even without bioscrape?

Inside CRN.simulate_with_bioscrape_via_sbml(...) put a try catch for import bioscrape?

**Comment by zoltuz** [comment]
I understand the preference for bioscrape as the main biocircuit simulator and the need to show some action in the examples, but I think BioCRNPyler should remain simulator agnostic, as it is just a compiler. 

From an outsider point of view, when you install BioCRNPyler with pip (soon we have that)
```terminal
pip install biocrnplyer
```
The example folder won't come with the python package, any reference to bioscrape in the codebase is a potential landmine in that scenario. If anything, I'd remove simulate_with_bioscrape_via_sbml function. And have this use case:
```python
import biocrnplyer
sbml = CRN.get_sbml()
try:
    import bioscrape
    simulation_results = bioscrape.simulate_sbml(sbml)
except ModuleNotFoundError:
   print(bioscrape was not found, simulation skipped')
```

Having said that we can make a decision to make BioCRNPyler fully dependent on bioscrape (e.g. install it with the setup.py of this package or make it a git submodule of BioCRNPyler and fully integrate with the python package).

Yet another option would be a simulationManager inside BioCRNPyler, which would look for the available simulators and calls one of them.
```python
import biocrnplyer
sbml = CRN.get_sbml()
simulation_results = SimulationManager(sbml, preferred='bioscrape')
``` 
SimulationManager under the hood would look for the available simulator packages (bioscrape, roadrunner) and would call the corresponding interface. Only problem with this approach is the technology dept: every time any of the packages changes, we need to rewrite the interface as well. Fine with one or two simulators, horrendous with ten. 

In my opinion, we need to move one level up and create another python module, e.g. synbio pipeline, synbio plumber, etc, which starts to integrate the available tools (biocnrplyer, bioscrape, subsml in the first round) together. This way, we can avoid adding functionalities that are not the core scope of any of the tools. 

Let me know what you think!

**Comment by WilliamIX** [comment]
My thought is the following: why not make simulate_with_bioscrape(...) have that try and catch statement inside of it? Ideally in such a way that Travis and other testing tools won't error out.

I also like the idea of a simulation manager - the main case here is precisely examples: we want people to see the output of their code. for non-developers, this is essential.

**Comment by ayush9pandey** [comment]
I agree with Zoltan that we should have biocrnpyler be simulator agnostic. But I'd be interested in hearing the downsides to try, except statements in simulate_with_bioscrape function (assuming that having try except will fix the problem).

**Comment by zoltuz** [comment]
We can and (frankly we should) monkey patch the code with try-except statement around bioscrape for now. 
But this is just treating the symptoms, the real problem is the dependency we try to bake into the code. 

@WilliamIX you haven't commented on the third option, creating a simple tool which has all other tools (BioCRNPlyer, subsbml, bioscrape, etc) as dependencies. I think in the long run the separation of responsibilities gives us a more maintainable code.

**Comment by WilliamIX** [comment]
I think a "tool" to manage simulations that is only used by biocrnpyler is actually, in effect, part of biocrnpyler. I do like the idea of bundling that part off to the side so it's not integrated into the main code the same way we did for graph plotting. Optional dependencies are okay in my view.

**Comment by zoltuz** [comment]
#116 solved this for now
