### ISSUE TITLE
Need a basic starter example notebook / tutorial style for biocrnpyler?

### ISSUE THREAD

**Issue by ayush9pandey** [BuildACell/BioCRNPyler#96]
Currently, when I look at BioCRNpyler as a new user : What do I go and run first? There doesn't seem to be an obvious explainer style jupyter notebook that can act as a tutorial / "Start here".  We should have enough content to have this from BE240?

**Comment by WilliamIX** [comment]
Good suggestion - I will throw something together right now.

**Comment by zoltuz** [comment]
There are lots of files in the Old examples folder. Could we reuse any of them?

**Comment by WilliamIX** [comment]
yep, that is what I am doing - basically refactoring examples that already exist into a more organized structure. Not rewriting too many.

**Comment by ayush9pandey** [comment]
Thanks @WilliamIX  for refactoring the examples, i think this issue can be closed now.
