### ISSUE TITLE
How to handle older versions of packages?

### ISSUE THREAD

**Issue by ayush9pandey** [BuildACell/BioCRNPyler#97]
This is not really an issue with biocrnpyler but rather a question about how we would want to manage versioning. 

Since the last pull request, we decided to start updating biocrnpyler versions (updated from 0.2 -> 0.2.1). With every new pull request (depending on the size of changes), we should ideally be updating versions. 

The problem is that jupyter notebook continues to use the older version (because the older installed version still exists in site-packages). Possible solutions:

* Forcefully delete all older versions when installing newer version - We would need to write setup.py in a way that does this.?

* Overwrite the current version with the later version?

* Use a package versioning manager : For example: https://pypi.org/project/pbr/

Some related discussion : https://www.python.org/dev/peps/pep-0440/

I am not sure what is the best solution here...

@murrayrm @zoltuz any comments?

**Comment by zoltuz** [comment]
Something like this could solve the problem:
## new workflow
 1. A feature/bugfix starts on a separate branch in your repo, where you test it 
 2. When you are ready you open a PR onto the **development** branch (doesn't exist yet)
 3. After review, it gets merged into  **development**
## new deployment
 1. When a handful of changes accumulated on development we merge them to **master**
 2. merge commit on master triggers a script, which tags the commit version number (adjust setup.py as well), and uploads the new code to the pip database
 3. with pip install the user upgrades the code 

## user interface
The user can pip install from the pip repo
```
pip install biocrnplyer
```
 or directly from GitHub
```
pip install git+git://github.com/BuildACell/BioCRNPyler.git
```
I did this on goggle colab:
<img width="658" alt="Screenshot 2020-06-17 at 12 08 21" src="https://user-images.githubusercontent.com/17138838/84891386-b2858f80-b093-11ea-8517-9fc2771669ca.png">
As you can see you can select branches. (I think you can even select single commits or PRs)

**Comment by WilliamIX** [comment]
I do think this would solve the problem, and I've been wanted to switch having a master branch and development branch separately.

**Comment by ayush9pandey** [comment]
What does pip install do that is different than setup.py install in terms of versioning? How is it ensured that the latest version will be used - because on the user's site-packages there will be two different egg files with the two versions?

**Comment by zoltuz** [comment]
Probably nothing, but pip uninstall does purge the package, while there's no setup.py uninstall (unless we write one). [source](https://stackoverflow.com/questions/1550226/python-setup-py-uninstall)

About the versioning: our workflow and the code itself are still changing a lot until we figure them out, I don't think we will have a reliable versioning schema. 

Probably the best workflow for the users right now:
### first time
```
mkdir biocrnplyer
git clone https://github.com/BuildACell/BioCRNPyler.git biocrnplyer
cd biocrnplyer
pip install --user .
``` 
### getting an update
```
pip uninstall biocrnpyler
git pull upstream/master
pip install --user .
```

**Comment by ayush9pandey** [comment]
Got it! `pip uninstall` does the trick then :)
