### ISSUE TITLE
converting warnings.warn exception to logging.warning

### ISSUE THREAD

**Issue by zoltuz** [BuildACell/BioCRNPyler#98]
It seems that way users get confused by the way we notify them about particular runtime warnings. I think migrating (hiding) such warning to the log stream would be a better solution. 

Python docs also recommend the same approach:
https://docs.python.org/3/howto/logging.html#when-to-use-logging

Issue a warning regarding a particular runtime event 
 - warnings.warn() in library code if the issue is avoidable and the client application should be modified to eliminate the warning
- logging.warning() if there is nothing the client application can do about the situation, but the event should still be noted

**Comment by WilliamIX** [comment]
yeah, I think this is a good idea. I also wonder if there is a gentler way to do warnings (ie print outs) that people don't see as an error. In some cases, this can be helpful to give users feedback.

**Comment by WilliamIX** [comment]
Many of these are in bioscrape - in particular with ODEint. Lets put these in a log which is only printed if things truly fail.

**Comment by WilliamIX** [comment]
I created a Bioscrape PR to fix this - will comment when it is merged to check to see if it does the trick or if there are more things to remove.
