### ISSUE TITLE
typo correction

### ISSUE THREAD

**Issue by eldad-a** [BuildACell/BioCRNPyler#99]
[Michaelis-Menten kinetics](https://en.wikipedia.org/wiki/Michaelis%E2%80%93Menten_kinetics)

> MichalisMenten

should read
Micha**e**lisMenten

**Comment by zoltuz** [comment]
Hi eldad-a,

Thanks for catching it! Would you mind forking the code, changing the typo and open a pull request with the correct form? Many thanks!

Cheers,
Zoltan

**Comment by eldad-a** [comment]
Hi @zoltuz ,

Thanks for your contributions to this project!

I did :  #100 

Please read the message in the PR -- you cannot be too careful with this PR...

I leave it up to the maintainers to decide it is time to close this issue.

**Comment by zoltuz** [comment]
PR #100 addressed this problem. Thanks @eldad-a !
